
import '../../../../core/entity/meal_entity/meal_entity.dart';

class MealModel extends Meal {
  MealModel({
    required String idMeal,
    required super.strMeal,
    String? strMealAlternate,
     String? strCategory,
     String? strArea,
     String? strInstructions,
    super.strMealThumb,
    String? strYoutube,
    String? strSource,


    super.imageUrl,
    super.isFavorite,
    super.strIngredient1,
    super.strIngredient2,
    super.strIngredient3,
    super.strIngredient4,
    super.strIngredient5,
    super.strIngredient6,
    super.strIngredient7,
    super.strIngredient8,
    super.strIngredient9,
    super.strIngredient10,
    super.strIngredient11,
    super.strIngredient12,
    super.strIngredient13,
    super.strIngredient14,
    super.strIngredient15,
    super.strIngredient16,
    super.strIngredient17,
    super.strIngredient18,
    super.strIngredient19,
    super.strIngredient20,
    super.strMeasure1,
    super.strMeasure2,
    super.strMeasure3,
    super.strMeasure4,
    super.strMeasure5,
    super.strMeasure6,
    super.strMeasure7,
    super.strMeasure8,
    super.strMeasure9,
    super.strMeasure10,
    super.strMeasure11,
    super.strMeasure12,
    super.strMeasure13,
    super.strMeasure14,
    super.strMeasure15,
    super.strMeasure16,
    super.strMeasure17,
    super.strMeasure18,
    super.strMeasure19,
    super.strMeasure20,

  }) : super(
    id: idMeal,
    alternate: strMealAlternate,
    strCategory: strCategory,
    area: strArea,
    instructions: strInstructions,
    youtubeUrl: strYoutube,

    source: strSource,
  );


  factory MealModel.fromJson(Map<String, dynamic> json) {



    return MealModel(
      idMeal: json['idMeal'],
      strMeal: json['strMeal'],
      strMealAlternate: json['strMealAlternate'],
      strCategory: json['strCategory'],
      strArea: json['strArea'],
      strInstructions: json['strInstructions'],
      strMealThumb: json['strMealThumb'],
      strYoutube: json['strYoutube'],
      strSource: json['strSource'],
      strIngredient1: json['strIngredient1'],
      strIngredient2: json['strIngredient2'],
      strIngredient3: json['strIngredient3'],
      strIngredient4: json['strIngredient4'],
      strIngredient5: json['strIngredient5'],
      strIngredient6: json['strIngredient6'],
      strIngredient7: json['strIngredient7'],
      strIngredient8: json['strIngredient8'],
      strIngredient9: json['strIngredient9'],
      strIngredient10: json['strIngredient10'],
      strIngredient11: json['strIngredient11'],
      strIngredient12: json['strIngredient12'],
      strIngredient13: json['strIngredient13'],
      strIngredient14: json['strIngredient14'],
      strIngredient15: json['strIngredient15'],
      strIngredient16: json['strIngredient16'],
      strIngredient17: json['strIngredient17'],
      strIngredient18: json['strIngredient18'],
      strIngredient19: json['strIngredient19'],
      strIngredient20: json['strIngredient20'],
      strMeasure1: json['strMeasure1'],
      strMeasure2: json['strMeasure2'],
      strMeasure3: json['strMeasure3'],
      strMeasure4: json['strMeasure4'],
      strMeasure5: json['strMeasure5'],
      strMeasure6: json['strMeasure6'],
      strMeasure7: json['strMeasure7'],
      strMeasure8: json['strMeasure8'],
      strMeasure9: json['strMeasure9'],
      strMeasure10: json['strMeasure10'],
      strMeasure11: json['strMeasure11'],
      strMeasure12: json['strMeasure12'],
      strMeasure13: json['strMeasure13'],
      strMeasure14: json['strMeasure14'],
      strMeasure15: json['strMeasure15'],
      strMeasure16: json['strMeasure16'],
      strMeasure17: json['strMeasure17'],
      strMeasure18: json['strMeasure18'],
      strMeasure19: json['strMeasure19'],
      strMeasure20: json['strMeasure20'],
      imageUrl: json['imageUrl'],
    );
  }


}
